site_name: EDRA

nav:
  - Documento de Visão: "documento-visao/documento-visao.md"
  - Documento de Requisitos: "documento-requisitos/documento-requisitos.md"
  - Documento de Arquitetura: "documento-arquitetura/documento-arquitetura.md"
  - Documento de Plano de Testes: "documento-plano-testes/documento-plano-testes.md"
  - Atas de Reunião:
    - Ata 1: "atas-reuniao/ata-reuniao-1.md"
    - Ata 2: "atas-reuniao/ata-reuniao-2.md"
    - Ata 3: "atas-reuniao/ata-reuniao-3.md"

theme:
  name: material
  palette:
    scheme: default
    primary: green
    language: pt-BR
